name: Deploy a Cliente MX (SFTP)

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 游꿀 Deploy MX
    runs-on: ubuntu-latest

    steps:
      - name: 游뚴 Obtener c칩digo m치s reciente
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 游늭 Sincronizar archivos SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: access-5015726610.ud-webspace.de
          username: a124214
          password: (Cr3at3b1u3.MX!!)
          port: 22
          # En esta acci칩n, remote_path define d칩nde se suben los archivos
          remote_path: CreatblueDemoMX/wp-content/themes/child-theme/
